version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - data-volume:/data/db

  api: 
    build: server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017/secret

  nginx:
    build: client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
  
volumes:
  data-volume: